// src/lib/tools-data.js

export const tools = [
  {
    id: "passport-photo",
    title: "Passport photo maker",
    description: "Convert any photo to professional 300x300 passport size with standard borders.",
    iconName: "camera",
    href: "/tools/passport-photo",
    category: "Image",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "resume-scanner",
    title: "ATS resume scanner",
    description: "Scan your resume against job descriptions to improve your ats score.",
    iconName: "file-text",
    href: "/tools/resume-scanner",
    category: "Career",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "metadata-cleaner",
    title: "PDF Metadata Cleaner",
    description: "Remove hidden sensitive information and metadata from your PDF files instantly.",
    iconName: "shield-check", // Lucide icon
    href: "/tools/metadata-cleaner",
    category: "Privacy",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "safe-zone-checker",
    title: "Social Media Safe Zone",
    description: "Verify your profile and banner images against mobile and desktop safe areas for all major platforms.",
    iconName: "layout",
    href: "/tools/safe-zone-checker",
    category: "Image",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "privacy-blur",
    title: "Privacy Blur Redactor",
    description: "Mask sensitive data like emails, passwords, or faces from your screenshots and photos in seconds.",
    iconName: "eye-off",
    href: "/tools/privacy-blur",
    category: "Privacy",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "code-to-image",
    title: "Code Snippet to Image",
    description: "Transform your code snippets into beautiful, shareable snapshots with professional themes and frames.",
    iconName: "code",
    href: "/tools/code-to-image",
    category: "Developer",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "color-palette",
    title: "AI Color Palette Extractor",
    description: "Extract professional color palettes from any image and generate Tailwind CSS themes instantly.",
    iconName: "image",
    href: "/tools/color-palette",
    category: "Image",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "sql-mermaid",
    title: "SQL to Mermaid Diagram",
    description: "Convert your SQL 'CREATE TABLE' statements into beautiful Visual ER Diagrams using Mermaid.js.",
    iconName: "code",
    href: "/tools/sql-mermaid",
    category: "Developer",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "message-encryptor",
    title: "Private Message Encryptor",
    description: "Secure your sensitive notes and messages with industrial-grade AES-256 encryption before sharing.",
    iconName: "lock",
    href: "/tools/message-encryptor",
    category: "Privacy",
    status: "Active",
    launchedAt: "2026-03-13",
  },
  {
    id: "price-comparison",
    title: "Value for Money Calculator",
    description: "Find the best deal between two products by comparing their unit prices and total savings.",
    iconName: "shopping-bag",
    href: "/tools/price-comparison",
    category: "Finance",
    status: "Active",
    launchedAt: "2026-03-13",
  },
];