// src/components/resources/faq-content.jsx

"use client";

import { useState } from "react";
import Link from "next/link";
import {
    ChevronDown,
    ShieldCheck,
    Cpu,
    Palette,
    MessageSquare
} from "lucide-react";

export const FAQ_DATA = [
    {
        category: "Architecture & Data Privacy",
        icon: ShieldCheck,
        color: "text-emerald-500",
        items: [
            {
                q: "How does xdevutilities protect user data and files?",
                a: "We operate on a strict Zero-Persistent-Storage architecture. Client-side tools (like Privacy Blur, Safe Zone Checker, and Fair Price Estimator) process data 100% locally in your browser canvas. For cloud-powered utilities (like ATS Resume Scanner and PDF Metadata Cleaner), payloads are processed statelessly in volatile RAM and immediately wiped upon completion. We do not maintain user databases or track usage history."
            },
            {
                q: "Can I safely use the Private Message Encryptor for sensitive credentials?",
                a: "Yes. The Message Encryptor utilizes military-grade AES-256 bit symmetric cryptography executed via stateless endpoints. Your private passphrase and plaintext are never committed to any database, file system, or analytics pipeline. Only recipients with your unique secret passphrase can decrypt the resulting ciphertext."
            },
            {
                q: "Do I need to create an account to use the utilities?",
                a: "No, account registration is completely optional. All 10 utilities are instantly accessible without mandatory logins or paywalls. Registering an account is solely provided for users who wish to bookmark preferred tools or retain personalized workspace settings."
            },
            {
                q: "Why are all tools free to use?",
                a: "Our mission is to provide high-performance, distraction-free utilities that replace bloated, ad-ridden web software. To cover high-speed infrastructure costs while keeping tools free for everyone, the platform is supported by ethical, non-intrusive sponsorships and advertisements without selling user data."
            }
        ]
    },
    {
        category: "Developer & Code Engines",
        icon: Cpu,
        color: "text-blue-500",
        items: [
            {
                q: "Which SQL dialects are supported by SQL to Mermaid?",
                a: "The parser supports standard ANSI SQL CREATE TABLE statements from PostgreSQL, MySQL, SQLite, and Microsoft SQL Server. It automatically interprets table columns, primary keys, and data types into declarative Mermaid markdown and lossless, infinitely zoomable SVG vector diagrams."
            },
            {
                q: "How does the Code to Image Converter export high-resolution assets?",
                a: "Our engine uses Prism.js for syntax highlighting and renders the snapshot at 3x pixel density (Retina-ready) using the browser Canvas API. This prevents pixelation and ensures your code snippets remain crisp on high-DPI social feeds like LinkedIn and X (Twitter)."
            },
            {
                q: "How does Privacy Blur achieve seamless redaction?",
                a: "In addition to standard Gaussian Blur and solid Blackout masks, Privacy Blur features an 'Auto Match' algorithm. It samples surrounding perimeter pixels to fill the redacted box with the exact background color, seamlessly blending text or UI elements into the canvas."
            }
        ]
    },
    {
        category: "Design, Career & Commerce Tools",
        icon: Palette,
        color: "text-indigo-500",
        items: [
            {
                q: "What makes the ATS Resume Scanner different from keyword counters?",
                a: "Our scanner executes semantic natural language parsing rather than simple word counting. It checks structural resume sections (experience, contact details, education) and measures keyword density against the provided job description to evaluate true applicant tracking compatibility."
            },
            {
                q: "What dimensions are generated by the Passport Photo Maker?",
                a: "It produces a standard 300x300 pixel square JPEG crop formatted for digital ID portals and general visa applications. For optimal compliance, we always recommend uploading a portrait with a neutral expression taken against a plain, evenly lit white backdrop."
            },
            {
                q: "How does the Social Media Safe Zone Checker prevent profile overlap?",
                a: "Different viewports dynamically scale banner graphics and shift circular user avatars. Our tool maps real-time boundary overlays for LinkedIn, YouTube, X, and Instagram, highlighting 'Danger Zones' where mobile UI elements crop vital text or logos."
            },
            {
                q: "How does the Fair Price Estimator handle non-standard quantities?",
                a: "The calculator performs multi-unit dimensional analysis across weight (kg/g), volume (l/ml), and count (pcs). It determines the exact base-unit market cost from a standard reference item, revealing hidden retailer margins, rounding markups, and shrinkflation."
            }
        ]
    }
];

export default function FAQContent() {
    // প্রথম প্রশ্নটি ডিফল্টভাবে খোলা থাকবে যাতে ব্যবহারকারী দেখেই বোঝে এটি ক্লিক করে ড্রপডাউন হয়
    const [openIndex, setOpenIndex] = useState("0-0");

    const toggleAccordion = (id) => {
        setOpenIndex((prev) => (prev === id ? null : id));
    };

    const allFaqs = FAQ_DATA.flatMap((cat) => cat.items);

    return (
        <>
            <div className="space-y-16">
                {FAQ_DATA.map((category, catIdx) => (
                    <div key={catIdx} className="space-y-6">

                        {/* Category Header */}
                        <div className="flex items-center gap-3 border-b border-border pb-4">
                            <div className="p-2.5 bg-muted rounded-xl border border-border shadow-sm">
                                <category.icon size={20} className={category.color} />
                            </div>
                            <h2 className="text-xl sm:text-2xl font-bold text-foreground">
                                {category.category}
                            </h2>
                        </div>

                        {/* Interactive Accordion List */}
                        <div className="space-y-3">
                            {category.items.map((item, itemIdx) => {
                                const uniqueId = `${catIdx}-${itemIdx}`;
                                const isOpen = openIndex === uniqueId;

                                return (
                                    <div
                                        key={uniqueId}
                                        className={`rounded-2xl border transition-all duration-200 overflow-hidden ${isOpen
                                                ? "bg-card border-primary/30 shadow-sm"
                                                : "bg-card/60 hover:bg-card border-border hover:border-border/80"
                                            }`}
                                    >
                                        {/* Clickable Header Button */}
                                        <button
                                            type="button"
                                            onClick={() => toggleAccordion(uniqueId)}
                                            aria-expanded={isOpen}
                                            className="w-full p-5 sm:p-6 text-left flex items-center justify-between gap-4 transition-colors select-none"
                                        >
                                            <span className={`text-sm sm:text-base font-semibold leading-snug transition-colors ${isOpen ? "text-foreground" : "text-foreground/90"
                                                }`}>
                                                {item.q}
                                            </span>

                                            {/* Interactive Rotating Arrow */}
                                            <div className={`p-1 rounded-lg shrink-0 transition-transform duration-300 ${isOpen
                                                    ? "rotate-180 text-primary bg-primary/10"
                                                    : "text-muted-foreground bg-muted/50"
                                                }`}>
                                                <ChevronDown size={18} />
                                            </div>
                                        </button>

                                        {/* Smooth Expandable Answer */}
                                        {isOpen && (
                                            <div className="px-5 sm:px-6 pb-6 pt-1 text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed font-normal border-t border-border/40 animate-in fade-in slide-in-from-top-1 duration-200">
                                                {item.a}
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>

                    </div>
                ))}

                {/* Support Help Card */}
                <div className="mt-20 p-8 sm:p-12 bg-card text-card-foreground rounded-3xl border border-border shadow-sm text-center space-y-5 max-w-3xl mx-auto">
                    <div className="w-12 h-12 bg-primary/10 text-primary rounded-2xl flex items-center justify-center mx-auto mb-2">
                        <MessageSquare size={22} />
                    </div>
                    <h2 className="text-2xl font-bold text-foreground">
                        Still have questions or feature suggestions?
                    </h2>
                    <p className="text-sm text-muted-foreground max-w-md mx-auto leading-relaxed">
                        If you encounter a specific technical edge case or would like to request a new developer utility, feel free to reach out directly.
                    </p>
                    <div className="pt-2">
                        <Link
                            href="legal/contact"
                            className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground hover:opacity-90 rounded-xl text-sm font-semibold shadow-sm transition-all active:scale-[0.98]"
                        >
                            <MessageSquare size={16} />
                            <span>Contact Developer Support</span>
                        </Link>
                    </div>
                </div>
            </div>

            {/* Google SEO FAQ Structured Data */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "FAQPage",
                        "mainEntity": allFaqs.map((faq) => ({
                            "@type": "Question",
                            "name": faq.q,
                            "acceptedAnswer": {
                                "@type": "Answer",
                                "text": faq.a
                            }
                        }))
                    })
                }}
            />
        </>
    );
}